import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const ftRegola = localFont({
  src: [
    {
      path: "../../public/assets/fonts/FTRegolaNeueTrial-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FTRegolaNeueTrial-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FTRegolaNeueTrial-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FTRegolaNeueTrial-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FTRegolaNeueTrial-Heavy.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-ft-regola",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${ftRegola.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
